export const BRAND = "Značka zařízení - například Lenovo, Apple aj."
export const MODEL = "Model zařízení - př. Macbook Pro, Lenovo ThinkPad"
export const OPERATING_SYSTEM = "Vyber značku a verzi operačního systému - př. Windows 10"
export const MEMORY_TYPE = "SSD je v současné době nejrozšířenější technologií"
export const MEMORY_CAPACITY = "Vyber kapacitu vnitřní paměti v GB. Kapacita (velikost) pevného disku určuje, jak velké množství dat dokáže disk pojmout. "
export const RAM_CAPACITY = "Vyber Kapacitu operační paměti RAM"
export const CPU = "Vyber značku a verzi procesoru (Intel, AMD)"
export const CPU_FREQUENCY = "Taktovací frekvence se používá jako indikátor rychlosti procesoru, která se měří v hodinovém cyklu za sekundu"
export const CPU_CORES = "Vícejádrový procesor je mikroprocesor, který v jednom pouzdře nebo na jednom čipu integruje více CPU, říkáme jader"
export const GPU_TYPES = "Dedikovaná je samostatná grafická karta od zavedeného výrobce (NVIDIA, AMD). Integrovaná karta má nižší spotřebu a hodí se na kancelářskou činnost"
export const GPU_MEMORY = "Vyber kapacitu grafické karty v GB. Je základním parametrem grafické karty, čím větší kapacita, tím větší výkonový potenciál."
export const GPU_CHIP = "Čip grafické karty je základní stavební kámen, který určuje grafický výkon zařízení."
export const DIAGONAL = "Úhlopříčka displeje je vzdálenost mezi levým spodním a pravým horním rohem displeje. Úhlopříčka displeje se zpravidla udává v palcích, přičemž 1 palec = 2,54 cm."

